services:
  postgres:
    image: postgres:13
    restart: always
    container_name: interest-club-app
    environment:
      POSTGRES_DB: andrew
      POSTGRES_USER: andrew
      POSTGRES_PASSWORD: andrew
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: andrew123
      MINIO_ROOT_PASSWORD: andrew123
    volumes:
      - ./minio_data:/data
    command: server /data --console-address ":9001"

  minio-console:
    image: minio/console
    container_name: minio-console
    depends_on:
      - minio
    ports:
      - "9002:9001"
    environment:
      MINIO_ROOT_USER: andrew123
      MINIO_ROOT_PASSWORD: andrew123

volumes:
  postgres_data: